In [24]:
import pandas as pd
import numpy as np

In [25]:
s3_path = "s3://govt-commodity-price-data-tushar/commodity_prices_raw.csv"

In [26]:
df = pd.read_csv(s3_path)

In [27]:
df.head()

,State,District,Market,Commodity,Variety,Grade,Arrival_Date,Min_x0020_Price,Max_x0020_Price,Modal_x0020_Price
0,Gujarat,Surendranagar,Dhragradhra APMC,Cummin Seed(Jeera),Cummin Seed(Jeera),Local,12/01/2026,19750.0,21150.0,20500.0
1,Gujarat,Surendranagar,Dhragradhra APMC,Groundnut,Seed,Local,12/01/2026,7575.0,7575.0,7575.0
2,Gujarat,Surendranagar,Dhragradhra APMC,Guar Seed(Cluster Beans Seed),Whole,Local,12/01/2026,4625.0,4625.0,4625.0
3,Rajasthan,Jodhpur Rural,Osiyan Mathania APMC,Mustard,Other,Local,12/01/2026,6200.0,6300.0,6250.0
4,Assam,Nagaon,Dhing APMC,Tomato,Tomato,FAQ,12/01/2026,2200.0,2450.0,2350.0

In [28]:
df.tail()

,State,District,Market,Commodity,Variety,Grade,Arrival_Date,Min_x0020_Price,Max_x0020_Price,Modal_x0020_Price
7004,West Bengal,Darjeeling,Karsiyang(Matigara) APMC,Squash(Chappal Kadoo),Other,FAQ,12/01/2026,1200.0,1400.0,1300.0
7005,West Bengal,Darjeeling,Darjeeling APMC,Cabbage,Other,FAQ,12/01/2026,2300.0,2500.0,2400.0
7006,Himachal Pradesh,Kangra,SMY Dharamshala,Cauliflower,Cauliflower,FAQ,12/01/2026,1500.0,2000.0,1750.0
7007,Himachal Pradesh,Kangra,SMY Dharamshala,Cabbage,Cabbage,FAQ,12/01/2026,1000.0,1200.0,1100.0
7008,Himachal Pradesh,Kangra,SMY Dharamshala,Coriander(Leaves),Coriander,FAQ,12/01/2026,2500.0,3000.0,2750.0

In [29]:
data = df.copy()

In [30]:
data.columns

Index(['State', 'District', 'Market', 'Commodity', 'Variety', 'Grade',
       'Arrival_Date', 'Min_x0020_Price', 'Max_x0020_Price',
       'Modal_x0020_Price'],
      dtype='object')

In [31]:
data.columns = (
    df.columns
        .str.strip()
        .str.title()
        .str.replace("_X0020_","_")
        .str.replace(" ","_")
)

In [32]:
data.columns

Index(['State', 'District', 'Market', 'Commodity', 'Variety', 'Grade',
       'Arrival_Date', 'Min_Price', 'Max_Price', 'Modal_Price'],
      dtype='object')

In [33]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7009 entries, 0 to 7008
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   State         7009 non-null   object
 1   District      7009 non-null   object
 2   Market        7009 non-null   object
 3   Commodity     7009 non-null   object
 4   Variety       7009 non-null   object
 5   Grade         7009 non-null   object
 6   Arrival_Date  7009 non-null   object
 7   Min_Price     7009 non-null   float64
 8   Max_Price     7009 non-null   float64
 9   Modal_Price   7009 non-null   float64
dtypes: float64(3), object(7)
memory usage: 547.7+ KB

### there is no null values but arrival date is in objects.

In [34]:
data["Arrival_Date"] = pd.to_datetime(data["Arrival_Date"], dayfirst=True)

In [35]:
data["Arrival_Date"].dtype

dtype('<M8[ns]')

In [36]:
price_cols = ["Min_Price", "Max_Price", "Modal_Price"]

data[price_cols] = data[price_cols].apply(
    pd.to_numeric, errors="coerce"
)

In [37]:
data.isnull().sum()

State           0
District        0
Market          0
Commodity       0
Variety         0
Grade           0
Arrival_Date    0
Min_Price       0
Max_Price       0
Modal_Price     0
dtype: int64

In [38]:
data.duplicated().sum()

np.int64(0)

In [39]:
data = data.dropna(subset=["Modal_Price"])

In [40]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7009 entries, 0 to 7008
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   State         7009 non-null   object
 1   District      7009 non-null   object
 2   Market        7009 non-null   object
 3   Commodity     7009 non-null   object
 4   Variety       7009 non-null   object
 5   Grade         7009 non-null   object
 6   Arrival_Date  7009 non-null   datetime64[ns]
 7   Min_Price     7009 non-null   float64
 8   Max_Price     7009 non-null   float64
 9   Modal_Price   7009 non-null   float64
dtypes: datetime64[ns](1), float64(3), object(6)
memory usage: 547.7+ KB

In [41]:
data.describe()

              Arrival_Date      Min_Price      Max_Price    Modal_Price
count                 7009    7009.000000    7009.000000    7009.000000
mean   2026-01-12 00:00:00    4105.004421    4733.878486    4425.871385
min    2026-01-12 00:00:00       2.600000       2.870000       2.750000
25%    2026-01-12 00:00:00    2200.000000    2500.000000    2450.000000
50%    2026-01-12 00:00:00    3500.000000    4000.000000    3750.000000
75%    2026-01-12 00:00:00    5000.000000    5500.000000    5200.000000
max    2026-01-12 00:00:00  150000.000000  150000.000000  150000.000000
std                    NaN    4465.629682    4994.166445    4729.483556

In [42]:
data.to_csv("commodity_prices_cleaned.csv", index=False)

In [43]:
data.to_csv(
    "s3://govt-commodity-price-data-tushar/processed/commodity_prices_cleaned.csv",
    index=False
)

In [44]:
from sqlalchemy import create_engine

In [45]:
#create mysql connection
engine = create_engine(
    "mysql+mysqlconnector://root:153182#Tushar@localhost:3306/govt_commodity_analysis"
)

In [46]:
data.to_sql(
    name="commodity_prices",
    con=engine,
    if_exists="replace",
    index=False
)

print("Data loaded into MySQL successfully")

Data loaded into MySQL successfully